name_or_path: /mnt/scratch/y/yangyh/models/meta-llama/Llama-2-7b-hf
tokenizer_name_or_path: /mnt/scratch/y/yangyh/models/meta-llama/Llama-2-7b-hf
archive: null
block_name: LlamaDecoderLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16