name_or_path: /mnt/scratch/y/yangyh/models/meta-llama/Llama-3.2-3B
tokenizer_name_or_path: /mnt/scratch/y/yangyh/models/meta-llama/Llama-3.2-3B
archive: null
block_name: LlamaDecoderLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16