name_or_path: /mnt/scratch/y/yangyh/models/LLM-Research/Meta-Llama-3-8B
tokenizer_name_or_path: /mnt/scratch/y/yangyh/models/LLM-Research/Meta-Llama-3-8B
archive: null
block_name: LlamaDecoderLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16